name: TiraBeauty Automation CI/CD

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx2048m
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Setup Display
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Verify installations
      run: |
        mvn --version
        google-chrome --version
        chromedriver --version
        echo "DISPLAY=$DISPLAY"

    - name: Clean and compile
      run: mvn clean compile

    - name: Run tests with headless mode
      run: |
        export DISPLAY=:99
        mvn test -Dheadless=true
      continue-on-error: true

    - name: List generated files
      if: always()
      run: |
        echo "=== Generated directories and files ==="
        find . -name "target" -o -name "test-output" -o -name "screenshots" -o -name "allure-results" | head -20
        echo "=== Target directory contents ==="
        ls -la target/ || echo "target/ directory not found"
        echo "=== Test-output directory contents ==="
        ls -la test-output/ || echo "test-output/ directory not found"
        echo "=== Screenshots directory contents ==="
        ls -la screenshots/ || echo "screenshots/ directory not found"
        echo "=== Allure-results directory contents ==="
        ls -la allure-results/ || echo "allure-results/ directory not found"

    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots
        path: |
          screenshots/
          test-output/screenshots/
        retention-days: 7

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          test-output/
        retention-days: 7

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30