name: TiraBeauty Automation CI/CD

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC

env:
  MAVEN_OPTS: -Xmx2048m

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      if: matrix.browser == 'chrome'

    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
      if: matrix.browser == 'firefox'

    - name: Verify Maven installation
      run: mvn --version

    - name: Clean and compile
      run: mvn clean compile

    - name: Run tests
      run: mvn test -Dbrowser=${{ matrix.browser }}
      continue-on-error: true

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: allure-history

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-${{ matrix.browser }}
        path: allure-results/
        retention-days: 30

    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-${{ matrix.browser }}
        path: screenshots/
        retention-days: 7

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.browser }}
        path: |
          target/surefire-reports/
          test-output/
        retention-days: 7

  deploy-reports:
    needs: test
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Allure Results
      uses: actions/download-artifact@v4
      with:
        pattern: allure-results-*
        merge-multiple: true
        path: allure-results/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        destination_dir: reports