name: TiraBeauty Automation CI/CD

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx2048m

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}/chromedriver_linux64.zip"
        sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Verify installations
      run: |
        mvn --version
        google-chrome --version
        chromedriver --version

    - name: Clean and compile
      run: mvn clean compile

    - name: Run tests
      run: mvn test
      continue-on-error: true

    - name: List generated files
      if: always()
      run: |
        echo "=== Generated directories and files ==="
        find . -name "target" -o -name "test-output" -o -name "screenshots" -o -name "allure-results" | head -20
        echo "=== Target directory contents ==="
        ls -la target/ || echo "target/ directory not found"
        echo "=== Test-output directory contents ==="
        ls -la test-output/ || echo "test-output/ directory not found"
        echo "=== Screenshots directory contents ==="
        ls -la screenshots/ || echo "screenshots/ directory not found"
        echo "=== Allure-results directory contents ==="
        ls -la allure-results/ || echo "allure-results/ directory not found"

    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots
        path: |
          screenshots/
          test-output/screenshots/
        retention-days: 7

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          test-output/
        retention-days: 7

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30